#!/bin/bash 

ADDONS="Color       "
ADDONS+="Filters "
ADDONS+="HoughTransform "
ADDONS+="Chabardes "
ADDONS+="StochasticWS "
ADDONS+="FFT "
ADDONS+="ZhangSkel "
ADDONS+="Parsimonious "
OTHER=

TEST=OFF
PACKAGE=OFF
DOC=OFF
DEVDOC=OFF

ARCH=generic

OPT_ADDONS=
for addon in $ADDONS
do 
    OPT_ADDONS+=" -DADDON_${addon}:BOOL=ON"
done

OPT=" -DADDITIONAL_SEARCH_PATHS:STRING=$CONDA_PREFIX \
         -DCONDA_PREFIX:STRING=$CONDA_PREFIX"


NUMPY_INCLUDES=`python -c "import numpy; print(numpy.get_include())"`


OPT="$OPT 
-Wno-dev
  -DCMAKE_INSTALL_PREFIX:STRING=$PREFIX
  -DBUILD_TEST:BOOL=$TEST
  -DBUILD_PACKAGE:BOOL=$PACKAGE
  -DTARGET_ARCHITECTURE:STRING=$ARCH
  -DUSE_64BIT_IDS:BOOL=ON
  -DUSE_CURL:BOOL=ON
  -DUSE_FREETYPE:BOOL=ON
  -DUSE_JPEG:BOOL=ON
  -DUSE_NUMPY:BOOL=ON
  -DUSE_OPEN_MP:BOOL=ON
  -DUSE_OPTIMIZATION:BOOL=OFF
  -DUSE_PNG:BOOL=ON
  -DUSE_QT:BOOL=ON
  -DUSE_TIFF:BOOL=ON
  -DBUILD_DOC:BOOL=$DOC
  -DVERBOSE_OPTIMIZATION:BOOL=OFF
  -DWRAP_PYTHON:BOOL=ON
  -DCMAKE_CXX_FLAGS:STRING=$CXX_FLAGS
  -DPYTHON_NUMPY_INCLUDE_DIR:PATH=${NUMPY_INCLUDES}
"

mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=${PREFIX} ${OPT}
make 
make install 