package:
  name: pymicro
  version: 0.5.1

source:
  git_rev: 
  git_url: https://github.com/heprom/pymicro.git

requirements:
  build:
    - python 
    - numpy 
    - scipy
    - sympy  
    - scikit-image
    - matplotlib
    - vtk 
    - lxml 
    - pytables
    - h5py 

  run:
    - python
    - numpy 
    - scipy 
    - sympy 
    - scikit-image
    - matplotlib
    - vtk 
    - lxml 
    - pytables
    - h5py 


  